---
title: "Taming Thymeleaf update for Thymeleaf 3.1.2"
date: 2023-10-19
draft: false
tags: ["spring-boot", "thymeleaf", "alpine"]
keywords: []
---
:source-highlighter: rouge
:rouge-css: style
:rouge-style: github
:imagesdir: /images
:icons: font
:toc: macro
:table-caption!:
:2c: ::
:underscore: _

https://github.com/thymeleaf/thymeleaf/milestone/69?closed=1[Thymeleaf 3.1.2] was released recently and is inluded in Spring Boot https://github.com/spring-projects/spring-boot/releases/tag/v3.0.10[3.0.10] and https://github.com/spring-projects/spring-boot/releases/tag/v3.1.3[3.1.3].
For https://github.com/thymeleaf/thymeleaf/commit/dd01397c785d7d34049eecd67440aef52398599d[security reasons], it is no longer allowed for a Thymeleaf template to directly access `org.springframework.web.servlet.support.ServletUriComponentsBuilder`.

This was used in my https://www.wimdeblauwe.com/books/taming-thymeleaf/[Taming Thymeleaf] book to build a generic fragment that can be used for pagination controls.

If you still use it, you get this exception while running the application:

[source]
----
org.springframework.expression.EvaluationException:
Access is forbidden for type 'org.springframework.web.servlet.support.ServletUriComponentsBuilder' in this expression context.
----

The way to fix this is exposing the `ServletUriComponentsBuilder` as a Spring bean using `@RequestScope`:

[source,java]
.com.tamingthymeleaf.application.infrastructure.web.WebMvcConfiguration
----
    @Bean
    @RequestScope
    public ServletUriComponentsBuilder urlBuilder() {
        return ServletUriComponentsBuilder.fromCurrentRequest();
    }
----

You can now replace `urlBuilder.fromCurrentRequest()` with `@urlBuilder` in the template itself.

To view the changes in context, check out https://github.com/wimdeblauwe/taming-thymeleaf-sources/commit/0bf0f8ad5cf35dba692d2b6fafa7aeeff8038315[this commit] on GitHub.

== Conclusion

Using Thymeleaf 3.1.2 needs a small change to the demo application of Taming Thymeleaf, but should be easy to apply given the above explanation.

If you have any questions or remarks, feel free to post a comment at https://github.com/wimdeblauwe/wimdeblauwe.com/discussions[GitHub discussions].
